name: Release

on:
  workflow_call:
    inputs:
      dry-run:
        description: 'Compiles the app but does not upload artifacts to distribution server'
        default: false
        required: false
        type: boolean
    secrets:
      GH_TOKEN:
        required: true
      BUILD_CERTIFICATE_BASE64:
        required: true
      P12_PASSWORD:
        required: true
      KEYCHAIN_PASSWORD:
        required: true
      APPLE_IDENTITY:
        required: true
      VITE_APP_API:
        required: true
      VITE_START_PAGE_URL:
        required: true

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  draft_release:
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            arch: x64
            platform: win
          - os: macos-latest
            arch: x64
            platform: mac-x64
          - os: macos-latest
            arch: arm64
            platform: mac-arm64
          - os: ubuntu-latest
            arch: x64
            platform: linux

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Git LFS
        run: |
          git lfs install
          git lfs pull

      # 配置环境变量
      - name: Configure environment
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 1
          ELECTRON_MIRROR: "https://npmmirror.com/mirrors/electron/"
          NODE_PRE_GYP_MIRROR: "https://npmmirror.com/mirrors/node-pre-gyp/"
        run: |
          echo "Environment configured"
          if [ "${{ matrix.platform }}" == "mac-arm64" ]; then
            echo "ELECTRON_ARCH=arm64" >> $GITHUB_ENV
          elif [ "${{ matrix.platform }}" == "mac-x64" ] || [ "${{ matrix.platform }}" == "linux" ]; then
            echo "ELECTRON_ARCH=x64" >> $GITHUB_ENV
          fi

      # 缓存依赖
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache/electron
            ~/.cache/node-gyp
          key: ${{ runner.os }}-${{ matrix.arch }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.arch }}-npm-

      # macOS 特定设置
      - name: Setup macOS build tools
        if: startsWith(matrix.platform, 'mac')
        run: |
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -license accept
          brew install python@3.11 make gcc
          echo "PYTHON=/opt/homebrew/opt/python@3.11/bin/python3.11" >> $GITHUB_ENV
          /opt/homebrew/opt/python@3.11/bin/python3.11 -m pip install setuptools

      # Linux 特定设置
      - name: Setup Linux build tools
        if: matrix.platform == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y python3.11 python3-pip python3-dev build-essential libx11-dev libxkbfile-dev libsecret-1-dev
          sudo ln -sf /usr/bin/python3.11 /usr/bin/python3
          python3 -m pip install setuptools node-gyp

      # 设置 Node.js
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: Install native modules
        run: npm install --ignore-scripts sqlite3 electron

      - name: Rebuild native modules for macOS
        if: matrix.os == 'macos-latest'
        run: |
          npm rebuild sqlite3 --build-from-source --python=/opt/homebrew/opt/python@3.11/bin/python3.11

      - name: Rebuild native modules for Linux
        if: matrix.platform == 'linux'
        run: |
          npm rebuild sqlite3 --build-from-source --python=/usr/bin/python3 --arch=x64

      - name: Install dependencies
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 20
          max_attempts: 3
          retry_wait_seconds: 30
          command: npm ci --verbose

      # 构建原生模块 - macOS
      - name: Build native modules for macOS
        if: startsWith(matrix.platform, 'mac')
        run: |
          if [ "${{ matrix.platform }}" == "mac-arm64" ]; then
            echo "Building native modules for ARM64"
            npm run build:native-addon:mac-arm64
          elif [ "${{ matrix.platform }}" == "mac-x64" ]; then
            echo "Building native modules for x64"
            npm run build:native-addon:mac-x64
          fi
          ls -la ./packages/main/src/native-addon/build/Release/

      # 构建原生模块 - Linux
      - name: Build native modules for Linux
        if: matrix.platform == 'linux'
        run: |
          echo "Building native modules for Linux x64"
          cd ./packages/main/src/native-addon
          node-gyp clean
          node-gyp configure --arch=x64
          node-gyp build --arch=x64
          cd ../../..
          ls -la ./packages/main/src/native-addon/build/Release/

      # 安装 Apple 证书（仅 macOS）
      - name: Install Apple certificates
        if: startsWith(matrix.platform, 'mac')
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          APPLE_IDENTITY: ${{ secrets.APPLE_IDENTITY }}
        run: |
          CERTIFICATE_PATH=$HOME/certificates
          KEYCHAIN_PATH=$HOME/Library/Keychains/build.keychain-db
          mkdir -p $CERTIFICATE_PATH
          echo "$BUILD_CERTIFICATE_BASE64" | base64 -D > $CERTIFICATE_PATH/certificate.p12
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security set-keychain-settings -t 3600 -u build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security import $CERTIFICATE_PATH/certificate.p12 -k build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain

      # 创建环境配置
      - name: Create .env.production.local
        run: |
          echo "VITE_APP_API=${{ secrets.VITE_APP_API }}" > .env.production.local
          echo "VITE_START_PAGE_URL=${{ secrets.VITE_START_PAGE_URL }}" >> .env.production.local

      # 构建项目
      - name: Build Project
        run: npm run build

      # 构建和发布 - Windows
      - name: Build and Publish for Windows
        if: matrix.platform == 'win'
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_wait_seconds: 30
          shell: bash
          command: npx electron-builder --win --config .electron-builder.config.js --publish always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          BUILD_TIME: ${{ github.run_number }}

      # 构建和发布 - macOS x64
      - name: Build and Publish for macOS x64
        if: matrix.platform == 'mac-x64'
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_wait_seconds: 30
          shell: bash
          command: npx electron-builder --mac --x64 --config .electron-builder.config.js --publish always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          BUILD_TIME: ${{ github.run_number }}
          APPLE_IDENTITY: ${{ secrets.APPLE_IDENTITY }}

      # 构建和发布 - macOS arm64
      - name: Build and Publish for macOS arm64
        if: matrix.platform == 'mac-arm64'
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_wait_seconds: 30
          shell: bash
          command: npx electron-builder --mac --arm64 --config .electron-builder.config.js --publish always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          BUILD_TIME: ${{ github.run_number }}
          APPLE_IDENTITY: ${{ secrets.APPLE_IDENTITY }}

      # 构建和发布 - Linux AppImage
      - name: Build and Publish for Linux AppImage
        if: matrix.platform == 'linux'
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_wait_seconds: 30
          shell: bash
          command: npx electron-builder --linux appimage --x64 --config .electron-builder.config.js --publish always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          BUILD_TIME: ${{ github.run_number }}
